export const JOKES_SET_CATEGORIES: 'JOKES_SET_CATEGORIES' = 'JOKES_SET_CATEGORIES';
export const JOKES_SET_JOKES: 'JOKES_SET_JOKES' = 'JOKES_SET_JOKES';

export const JOKES_ADD_FAVOURITE: 'JOKES_ADD_FAVOURITE' = 'JOKES_ADD_FAVOURITE';
export const JOKES_REMOVE_FAVOURITE: 'JOKES_REMOVE_FAVOURITE' = 'JOKES_REMOVE_FAVOURITE';

export const JOKES_SET_LOADING: 'JOKES_SET_LOADING' = 'JOKES_SET_LOADING';

export const JOKES_SET_ERROR: 'JOKES_SET_ERROR' = 'JOKES_SET_ERROR';

export const MENU_OPEN: 'MENU_OPEN' = 'MENU_OPEN';
export const MENU_CLOSE: 'MENU_CLOSE' = 'MENU_CLOSE';