export const JOKES_SET_CATEGORIES: 'JOKES_SET_CATEGORIES' = 'JOKES_SET_CATEGORIES';
export const JOKES_SET_JOKES: 'JOKES_SET_JOKES' = 'JOKES_SET_JOKES';

export const JOKES_ADD_FAVOURITE: 'JOKES_ADD_FAVOURITE' = 'JOKES_ADD_FAVOURITE';
export const JOKES_REMOVE_FAVOURITE: 'JOKES_REMOVE_FAVOURITE' = 'JOKES_REMOVE_FAVOURITE';